### PR TITLE
Adds information about the path on error

### PR DESCRIPTION
**Pull request by JbIPS**
Keeps track of the xpath in the validated var to give a more verbose error.

Updates TU and documentation

### CODE REVIEW

**Comment by back2dos** [comment]
Wow! This is pull request porn :D

I'm going to let Kevin do the honors ;)

There's one *actual* problem I see: If you reuse the same validator instance, the path doesn't get reset after an exception. My suggestion would be to keep the path immutable and pass it on the stack (add it to the argument list in `wrap`).

I would also suggest keeping track of array indices in the path, because if you validate a long list of stuff, knowing just the field names is not that helpful.

**Comment by JbIPS** [comment]
> If you reuse the same validator instance, the path doesn't get reset after an exception. 

I'm not following you here, it looks like a new instance **is** created each time or did I missed a use case in the UT? 

And I'll try to add the index as a element in the path array (as a string if it's OK).

**Comment by back2dos** [comment]
>> If you reuse the same validator instance, the path doesn't get reset after an exception. 
>
> I'm not following you here, it looks like a new instance **is** created each time or did I missed a use case in the UT? 

The `Validation` class is a facade. In theory you can write:

```haxe
var validator = new tink.validation.Validator<TheStructure>();
validator.validate(o1);
validator.validate(o2);
```

I'm not sure it's a super important use case to consider. Upon looking at it again, the trivial solution would be to init `path` in the generated  `validate` / `extract` rather than the constructor and leave the rest as it is. 

> And I'll try to add the index as a element in the path array (as a string if it's OK). 

I think it is. After all the path is meant for displaying to the user, right?

**Comment by JbIPS** [comment]
I added your case and reset the path when calling `extract` or `validation`. This should be clearer now 😄

**Comment by kevinresol** [comment]
This is super awesome, thanks!

**Pull request merged**
